@baseUrl=http://localhost:3000

### login api

# @name login
POST {{baseUrl}}/auth/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "username": "tarang",
  "password": "tarang"
}

### profile api

@token = {{login.response.body.access_token}}

GET {{baseUrl}}/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### end of doc
